### ISSUE TITLE
Add Book Skechy Scheme

### ISSUE THREAD

**Issue by jcubic** [schemeorg/community#15]
This is a great book about Scheme, a crash course intro to Scheme.

![sketchy-scheme](https://github.com/schemeorg-community/monorepo/assets/280241/24251ba8-5186-4635-9705-4ba412e341e5)

https://www.t3x.org/sketchy/

3rd edition of the book called Sketchy Lisp is available on Archive.org

https://archive.org/details/sketchy-lisp

**Comment by lassik** [comment]
Thanks! I added a basis infobox to books.scheme.org (see commit above). Feel free to send a PR adding more details.

**Comment by jcubic** [comment]
Great, looks good.
