### ISSUE TITLE
Fix links to book "Teach Yourself Scheme in Fixnum Days"

### ISSUE THREAD

**Issue by mvuets** [schemeorg/community#19]
At <https://books.scheme.org/> there are three links to three editions
of the book. However, two of them incorrectly point to a completely
different book (TSPL). Moreover, there seems to be only a single,
"rolling" edition of TYSIFD altogether.

(I'm too lazy to fork a repo to make and send a PR.
Please see an enclosed patch file instead.)

[fix-tyscheme-book-links.txt](https://github.com/user-attachments/files/15593721/fix-tyscheme-book-links.txt)

**Comment by arthurgleckler** [comment]
Thank you.  Merged and pushed.

I also add alt attributes for all the cover images while I was at it.
