### ISSUE TITLE
CHICKEN page https://get.scheme.org/chicken/ links to Chez resources incl docker

### ISSUE THREAD

**Issue by spdegabrielle** [schemeorg/community#20]
CHICKEN page https://get.scheme.org/chicken/ links to Chez resources incl docker.  I'm unable to determine where the source for https://get.scheme.org/chicken/ is held - if I could find the repo I would do the PR to fix myself.

**Comment by lassik** [comment]
That page was unfinished work which I uploaded to the production site and neglected to delete. It wat not intentionally linked to from any public page.

Now deleted.
