### ISSUE TITLE
Link to R5RS Revised PDF is Broken

### ISSUE THREAD

**Issue by 9t8** [schemeorg/community#3]
> Unofficial documents with errata corrected (PDF): [R5RS](https://standards.scheme.org/unofficial/errata-corrected-r5rs.pdf)

The link returns a 404 not found.

**Comment by 9t8** [comment]
The R3RS pdf link seems to have gone down as well.

**Comment by arthurgleckler** [comment]
Where did you find the R5RS link?  The one I found at [standards.scheme.org](https://standards.scheme.org/) is working fine: [r5rs](https://standards.scheme.org/unofficial/errata-corrected-r5rs/).

The R3RS link on that page is failing for me, too.

**Comment by 9t8** [comment]
The broken link is the one above it, pointing to a .pdf file.

**Comment by arthurgleckler** [comment]
Lassi, is there a more recent copy of this repo somewhere?  I just pulled from this copy, and there are many more things broken than appear to be broken on [standards.scheme.org](https://standards.scheme.org/).  For example, the entire `official/` directory is missing.  I'm probably missing something obvious.

**Comment by lassik** [comment]
Fix pushed to git and website; see today's commits.

The PDF files in `official/` and `unofficial/` are from https://github.com/schemedoc/standards, which is waiting to be polished.

**Comment by 9t8** [comment]
> Where did you find the R5RS link? The one I found at [standards.scheme.org](https://standards.scheme.org/) is working fine: [r5rs](https://standards.scheme.org/unofficial/errata-corrected-r5rs/).

It's since been removed from the webpage, but the "corrected" HTML r5rs does not seem to have been corrected.

**Comment by lassik** [comment]
AFAIK there is no errata-corrected HTML or PDF version of R5RS. There may be a non-corrected HTML version but I don't know where.

**Comment by lassik** [comment]
To be clear, it'd be great if we had all this stuff, but it takes effort. More volunteers are welcome.
